### ISSUE TITLE
Eldewrito Update Launcher not working

### ISSUE THREAD

**Issue by labrat14** [ElDewrito/DoritoMenu#18]
I have installed and reinstalled Eldewrito several times with no difference, I tried to install all through The M downloader and through the firefox add-on. No difference, I have tried on ALL attempts to remove the preference.dat file. No difference. The issue happens when I launch the updater and click "play game". It loads and then does nothing. Nothing shows up on my task manager, nor any background appliances. I really do not know what to do.

**Comment by dany5639** [comment]
This has nothing to do with DoritoMenu.
