### ISSUE TITLE
Master server list is too big for its menu, sticks when opening other menus

### ISSUE THREAD

**Issue by JazRav** [ElDewrito/DoritoMenu#2]
The master server list is to big
![2015-07-15_20-13-08](https://cloud.githubusercontent.com/assets/3123226/8713425/0848507e-2b2e-11e5-8d72-00323f1eda30.jpg)

![2015-07-15_20-01-57](https://cloud.githubusercontent.com/assets/3123226/8713431/17b4aa62-2b2e-11e5-96d6-d1579ed8eef6.jpg)

**Comment by Limited55** [comment]
Menu is still heavy WIP (only an hour spent on it so far). Known issue.

**Comment by Limited55** [comment]
This has been fixed and is now live
