### ISSUE TITLE
Inaccurate player count

### ISSUE THREAD

**Issue by Shadowfita** [ElDewrito/DoritoMenu#7]
DoritoMenu/blob/master/client/views/js/ListServers.js

The playerCount function seems to be counting blank names/players which have left servers, a simple way to fix it would be read the servers 'numPlayers' rather than the length of the players array.

**Comment by dark-c0de** [comment]
This is fixed in https://github.com/ElDewrito/DoritoMenu/commit/c863976b95be6953747f3757f0d7346dce9efb80

Thanks!
